### ISSUE TITLE
angular 5.2 compile issue

### ISSUE THREAD

**Issue by Romsan01** [sudheerj/primeng-extensions#1]
I am getting this error while trying to build it with webpack

[INFO] ERROR in src/main/webapp/app/primeng/menu/menu/menudemo.module.ts(28,9): Error during template compile of 'TestMenuDemoModule'
[INFO]   Function expressions are not supported in decorators in 'WizardModule'
[INFO]     'WizardModule' references 'ɵ2'
[INFO]       'ɵ2' contains the error at primeng-extensions/components/wizard/wizard.js.ts(134,21)
[INFO]         Consider changing the function expression into an exported function.

**Comment by Romsan01** [comment]
PROD build

**Comment by sudheerj** [comment]
Angular ngOnChanges doesn't accespt arrow functions or function expressions in that specific method. The work is progress.

**Comment by sudheerj** [comment]
The issue is fixed with 0.1.0 version.
