### ISSUE TITLE
npmjs version

### ISSUE THREAD

**Issue by jucasoft** [sudheerj/primeng-extensions#4]
I wanted to use your library, but I realized that the version on git (1.0.0) is different from that on npmjs.
I decided to use your source code in my project, I will put a note indicating where I got the code from.
I hope you do not mind

Why do I also find the * .js and * .d.ts files in the source code?

Thank's for your job

**Comment by sudheerj** [comment]
The latest version 1.0.0 is updated in npm registry with new fixes
